image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - deploy

before_script:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

deploy:
  stage: deploy
  only:
    - master
  script:
    - echo "Deploying to EC2 via docker-compose"
    - scp docker-compose.yml Dockerfile requirements.txt -r src ubuntu@$EC2_HOST:/home/ubuntu/app
    - ssh ubuntu@$EC2_HOST "
        cd /home/ubuntu/app &&
        docker compose down || true &&
        docker compose build &&
        docker compose up -d
      "